# wget https://github.com/docker-library/python/raw/master/3.5/Dockerfile
# sed -i -e 's|FROM buildpack-deps:jessie|FROM buildpack-deps:stretch|' -e 's|tcl |tcl gpg dirmngr |' Dockerfile
# docker build -t szepeviktor/python:3.5.2-stretch python
# docker run -t -i --rm --cap-add SYS_ADMIN --device /dev/fuse --entrypoint=/bin/bash szepeviktor/python:3.5.2-stretch
image: szepeviktor/python:3.5.2-stretch

pipelines:
  default:
    - step:
        script:
          - apt-get update -qq
          - apt-get install -q -y libfuse-dev libattr1-dev python3-sphinx python3-dev python3-pytest python3-pytest-catchlog pkg-config fuse cython3 python3-setuptools
#          - apt-get install -q -y mercurial
#          - hg clone https://szepeviktor@bitbucket.org/szepeviktor/python-llfuse && cd python-llfuse/
          - python3 setup.py build_cython
          - python3 setup.py build_ext --inplace
          - whoami && python3 -m pytest test/
          - python3 setup.py build_sphinx
          - python3 setup.py install
