image: debian

pipelines:
  default:
    - step:
        script:
          - apt-get update -qq
          - apt-get install -q -y libfuse-dev libattr1-dev python3-sphinx python3-dev python3-pytest python3-pytest-catchlog pkg-config fuse cython3 python3-setuptools
          - ln -s /usr/bin/cython3 /usr/bin/cython
          - python3 setup.py build_cython build_ext --inplace
          - python3 -m pytest test/
          - python3 setup.py build_sphinx
          - python3 setup.py install
